# Generated by Django 3.2.4 on 2021-06-10 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20210610_1129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='About',
            new_name='about',
        ),
    ]
