# Generated by Django 3.2.4 on 2021-06-10 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_about_profile_about'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Social_name',
            new_name='social_name',
        ),
    ]
